### ISSUE TITLE
Should not show deleted posts

### ISSUE THREAD

**Issue by klekanger** [klekanger/wordpress-gatsby-starter#11]
Add code for hiding deleted WP posts.

**Comment by w3bdesign** [comment]
Seems like a Gatsby cache issue. 

Do a `gatsby clean` and then do a `gatsby develop` and the deleted posts are not shown.

Haven't tested this in a production environment though. In a production environment you may try to delete the deployment cache and redeploy the site.

**Comment by klekanger** [comment]
That could be the issue. But I noticed this when running WP on my local machine, with support for incremental builds in Gatsby (then posts should disappear immediatly when deleting them). When deleting a post in WP, the post did not disappear from the front page of the Gatsby site. When I removed it from the trash in WP, the post disappeared.

**Comment by klekanger** [comment]
Tested this again now – and everything works as expected. Deleted posts are removed immediately from the front page. Must have been some caching issue or a strange bug of some sort. 

Closing this issue now.
