### ISSUE TITLE
Add archive link on front page

### ISSUE THREAD

**Issue by klekanger** [klekanger/wordpress-gatsby-starter#12]
Not possible to view more than the 6 first posts. Add an archive or "more posts" link on the front page to view the rest of the posts.

**Comment by w3bdesign** [comment]
Wouldn't it be a better idea to implement pagination?

I found some links regarding the topic:

https://spectrum.chat/gatsby-js/general/pagination-in-gatsbyjs-with-wordpress-as-cms~d331d4dd-3f64-4186-8b9f-7fb5ca3446b8

https://www.gatsbyjs.org/packages/gatsby-paginate/

https://dimitr.im/gatsby-pagination

**Comment by klekanger** [comment]
Solved (PR #16 )
